import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";

const CreateInput = z.object({
  customer_name: z.string().trim().min(1).max(60),
  customer_phone: z.string().trim().min(5).max(30),
  age: z.coerce.number().int().min(1).max(120),
  mood: z.string().trim().min(1).max(40),
  language: z.enum(["ar", "en"]).default("ar"),
  image_data_url: z.string().min(20).max(20_000_000), // base64 data URL
});

type PricingRow = {
  usd_per_credit: number;
  iqd_per_usd: number;
  tier_pdf_iqd: number;
  tier_printed_iqd: number;
  tier_video_iqd: number;
  print_cost_iqd: number;
  shipping_cost_iqd: number;
};

async function logEvent(
  orderId: string,
  step: string,
  model: string,
  operation: "chat" | "image",
  meta: { log_id: string | null; run_id: string | null; usage: { input_tokens?: number; output_tokens?: number; total_tokens?: number }; duration_ms: number },
  costUsd: number,
  imageCount: number,
  pricing: PricingRow,
  status: "success" | "error" = "success",
  errorMessage: string | null = null,
) {
  const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
  const cost_iqd = +(costUsd * Number(pricing.iqd_per_usd)).toFixed(2);
  const cost_credits = Number(pricing.usd_per_credit) > 0
    ? +(costUsd / Number(pricing.usd_per_credit)).toFixed(6)
    : 0;
  await supabaseAdmin.from("generation_events").insert({
    order_id: orderId,
    step,
    model,
    operation,
    aig_log_id: meta.log_id,
    aig_run_id: meta.run_id,
    input_tokens: meta.usage.input_tokens ?? 0,
    output_tokens: meta.usage.output_tokens ?? 0,
    total_tokens: meta.usage.total_tokens ?? ((meta.usage.input_tokens ?? 0) + (meta.usage.output_tokens ?? 0)),
    image_count: imageCount,
    cost_credits,
    cost_usd: +costUsd.toFixed(6),
    cost_iqd,
    status,
    error_message: errorMessage,
    duration_ms: meta.duration_ms,
  });
}

async function getPricing(): Promise<PricingRow> {
  const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
  const { data } = await supabaseAdmin.from("pricing_settings").select("*").eq("id", 1).maybeSingle();
  if (!data) {
    return {
      usd_per_credit: 0.1,
      iqd_per_usd: 1310,
      tier_pdf_iqd: 3000,
      tier_printed_iqd: 10000,
      tier_video_iqd: 25000,
      print_cost_iqd: 0,
      shipping_cost_iqd: 0,
    };
  }
  return data as PricingRow;
}

/**
 * Create the order draft: store character + image, return orderId.
 * The cover + first paragraph are generated by generatePreview (next step).
 */
export const createOrderDraft = createServerFn({ method: "POST" })
  .inputValidator((d: unknown) => CreateInput.parse(d))
  .handler(async ({ data }) => {
    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");

    // Decode data URL
    const m = data.image_data_url.match(/^data:(image\/[a-z+]+);base64,(.+)$/i);
    if (!m) throw new Error("Invalid image data URL");
    const mime = m[1];
    const ext = mime.split("/")[1].replace("jpeg", "jpg").split("+")[0];
    const buffer = Buffer.from(m[2], "base64");
    if (buffer.byteLength > 8 * 1024 * 1024) throw new Error("Image too large (max 8MB)");

    const id = crypto.randomUUID();
    const path = `uploads/${id}.${ext}`;
    const up = await supabaseAdmin.storage
      .from("story-uploads")
      .upload(path, buffer, { contentType: mime, upsert: false });
    if (up.error) throw new Error(up.error.message);

    const { data: ch, error: chErr } = await supabaseAdmin
      .from("characters")
      .insert({
        customer_name: data.customer_name,
        customer_phone: data.customer_phone,
        age: data.age,
        mood: data.mood,
        image_path: path,
        language: data.language,
      })
      .select("id")
      .single();
    if (chErr || !ch) throw new Error(chErr?.message || "Failed to create character");

    const { data: ord, error: ordErr } = await supabaseAdmin
      .from("orders")
      .insert({
        character_id: ch.id,
        customer_phone: data.customer_phone,
        status: "pending",
      })
      .select("id, order_number")
      .single();
    if (ordErr || !ord) throw new Error(ordErr?.message || "Failed to create order");

    return { orderId: ord.id as string, orderNumber: ord.order_number as number };
  });

const PreviewInput = z.object({ orderId: z.string().uuid() });

export const generatePreview = createServerFn({ method: "POST" })
  .inputValidator((d: unknown) => PreviewInput.parse(d))
  .handler(async ({ data }) => {
    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
    const { callChat, callImage, estimateTextCostUsd, estimateImageCostUsd } = await import("./ai-gateway.server");

    // Check if already generated
    const { data: existing } = await supabaseAdmin
      .from("generations")
      .select("*")
      .eq("order_id", data.orderId)
      .maybeSingle();
    if (existing?.first_paragraph && existing?.cover_image_path) {
      const signed = await supabaseAdmin.storage
        .from("story-covers")
        .createSignedUrl(existing.cover_image_path, 60 * 60);
      return {
        first_paragraph: existing.first_paragraph as string,
        cover_url: signed.data?.signedUrl ?? null,
      };
    }

    const { data: order } = await supabaseAdmin
      .from("orders")
      .select("id, character_id, characters(customer_name, age, mood, language)")
      .eq("id", data.orderId)
      .single();
    const ch = order?.characters as { customer_name: string; age: number; mood: string; language: string } | null;
    if (!ch) throw new Error("Order not found");

    const pricing = await getPricing();
    const isAr = ch.language === "ar";

    // 1) First paragraph (text)
    const textModel = "google/gemini-3-flash-preview";
    const sys = isAr
      ? "أنت كاتب قصص ساحر للجمهور العربي. اكتب فقرة افتتاحية قصيرة (3-4 جمل) تجذب القارئ بشدة دون كشف خاتمة القصة."
      : "You are a magical storyteller. Write a short opening paragraph (3-4 sentences) that hooks the reader without revealing the ending.";
    const prompt = isAr
      ? `اكتب فقرة افتتاحية لقصة عن بطل اسمه "${ch.customer_name}" في عمر ${ch.age}، بجو "${ch.mood}". اجعلها مشوّقة وحميمة.`
      : `Write an opening paragraph for a story about a hero named "${ch.customer_name}", age ${ch.age}, with a "${ch.mood}" vibe. Make it gripping and intimate.`;
    let first_paragraph = "";
    try {
      const chat = await callChat({
        model: textModel,
        messages: [
          { role: "system", content: sys },
          { role: "user", content: prompt },
        ],
      });
      first_paragraph = chat.content.trim();
      await logEvent(
        data.orderId,
        "first_paragraph",
        textModel,
        "chat",
        chat.meta,
        estimateTextCostUsd(textModel, chat.meta.usage),
        0,
        pricing,
      );
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      await logEvent(
        data.orderId,
        "first_paragraph",
        textModel,
        "chat",
        { log_id: null, run_id: null, usage: {}, duration_ms: 0 },
        0,
        0,
        pricing,
        "error",
        msg,
      );
      throw e;
    }

    // 2) Cover image
    const imgModel = "google/gemini-3.1-flash-image";
    const imgPrompt = isAr
      ? `غلاف كتاب فني وجميل لقصة "${ch.mood}" بطلها طفل/شخص اسمه ${ch.customer_name}. أسلوب رسم دافئ، ألوان غنية، تفاصيل سينمائية، عنوان عربي مكتوب: "حكاية ${ch.customer_name}".`
      : `A beautiful artistic book cover for a "${ch.mood}" story whose hero is named ${ch.customer_name}. Warm illustration style, rich colors, cinematic detail, title text: "The Story of ${ch.customer_name}".`;
    let cover_path = "";
    try {
      const img = await callImage({ model: imgModel, prompt: imgPrompt });
      cover_path = `covers/${data.orderId}.png`;
      const buf = Buffer.from(img.b64, "base64");
      const up = await supabaseAdmin.storage
        .from("story-covers")
        .upload(cover_path, buf, { contentType: "image/png", upsert: true });
      if (up.error) throw new Error(up.error.message);
      await logEvent(
        data.orderId,
        "cover_image",
        imgModel,
        "image",
        img.meta,
        estimateImageCostUsd(imgModel, 1),
        1,
        pricing,
      );
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      await logEvent(
        data.orderId,
        "cover_image",
        imgModel,
        "image",
        { log_id: null, run_id: null, usage: {}, duration_ms: 0 },
        0,
        0,
        pricing,
        "error",
        msg,
      );
      // Don't throw — first paragraph is still useful
    }

    await supabaseAdmin
      .from("generations")
      .upsert({
        order_id: data.orderId,
        first_paragraph,
        cover_image_path: cover_path || null,
      }, { onConflict: "order_id" });

    const cover_url = cover_path
      ? (await supabaseAdmin.storage.from("story-covers").createSignedUrl(cover_path, 60 * 60)).data?.signedUrl ?? null
      : null;

    return { first_paragraph, cover_url };
  });

const ConfirmInput = z.object({
  orderId: z.string().uuid(),
  tier: z.enum(["pdf", "printed", "video"]),
});

export const confirmTierAndPrepareWhatsapp = createServerFn({ method: "POST" })
  .inputValidator((d: unknown) => ConfirmInput.parse(d))
  .handler(async ({ data }) => {
    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
    const pricing = await getPricing();
    const amount =
      data.tier === "pdf"
        ? pricing.tier_pdf_iqd
        : data.tier === "printed"
          ? pricing.tier_printed_iqd
          : pricing.tier_video_iqd;
    const { data: ord, error } = await supabaseAdmin
      .from("orders")
      .update({ tier: data.tier, amount_iqd: amount, whatsapp_sent_at: new Date().toISOString() })
      .eq("id", data.orderId)
      .select("order_number, tier, amount_iqd")
      .single();
    if (error || !ord) throw new Error(error?.message || "Failed");
    return { order_number: ord.order_number, tier: ord.tier, amount_iqd: ord.amount_iqd };
  });

export const getOrderPublic = createServerFn({ method: "GET" })
  .inputValidator((d: unknown) => z.object({ orderId: z.string().uuid() }).parse(d))
  .handler(async ({ data }) => {
    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
    const { data: o } = await supabaseAdmin
      .from("orders")
      .select("id, order_number, tier, amount_iqd, status, characters(customer_name, mood, language)")
      .eq("id", data.orderId)
      .maybeSingle();
    return o;
  });

// ============ ADMIN ============

async function gate() {
  const { requireAdmin } = await import("./admin-session.server");
  await requireAdmin();
}

export const adminListOrders = createServerFn({ method: "GET" }).handler(async () => {
  await gate();
  const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
  const { data: orders } = await supabaseAdmin
    .from("orders")
    .select("id, order_number, tier, amount_iqd, status, customer_phone, created_at, characters(customer_name)")
    .order("created_at", { ascending: false })
    .limit(200);
  const { data: costs } = await supabaseAdmin
    .from("order_costs_v")
    .select("order_id, cost_iqd, gross_profit_iqd, margin_pct, total_tokens, images_generated, cost_credits, cost_usd");
  const byId = new Map((costs ?? []).map((c) => [c.order_id, c]));
  return (orders ?? []).map((o) => ({ ...o, cost: byId.get(o.id) ?? null }));
});

export const adminGetOrder = createServerFn({ method: "GET" })
  .inputValidator((d: unknown) => z.object({ orderId: z.string().uuid() }).parse(d))
  .handler(async ({ data }) => {
    await gate();
    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
    const [{ data: order }, { data: events }, { data: gen }, { data: cost }] = await Promise.all([
      supabaseAdmin
        .from("orders")
        .select("*, characters(*)")
        .eq("id", data.orderId)
        .single(),
      supabaseAdmin
        .from("generation_events")
        .select("*")
        .eq("order_id", data.orderId)
        .order("created_at", { ascending: true }),
      supabaseAdmin.from("generations").select("*").eq("order_id", data.orderId).maybeSingle(),
      supabaseAdmin.from("order_costs_v").select("*").eq("order_id", data.orderId).maybeSingle(),
    ]);
    let cover_url: string | null = null;
    let upload_url: string | null = null;
    if (gen?.cover_image_path) {
      const s = await supabaseAdmin.storage.from("story-covers").createSignedUrl(gen.cover_image_path, 60 * 60);
      cover_url = s.data?.signedUrl ?? null;
    }
    const ch = order?.characters as { image_path?: string | null } | null;
    if (ch?.image_path) {
      const s = await supabaseAdmin.storage.from("story-uploads").createSignedUrl(ch.image_path, 60 * 60);
      upload_url = s.data?.signedUrl ?? null;
    }
    return { order, events: events ?? [], gen, cost, cover_url, upload_url };
  });

export const adminUpdateStatus = createServerFn({ method: "POST" })
  .inputValidator((d: unknown) =>
    z.object({
      orderId: z.string().uuid(),
      status: z.enum(["pending", "paid", "delivered", "cancelled"]),
    }).parse(d),
  )
  .handler(async ({ data }) => {
    await gate();
    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
    const patch: Record<string, unknown> = { status: data.status };
    if (data.status === "paid") patch.paid_at = new Date().toISOString();
    if (data.status === "delivered") patch.delivered_at = new Date().toISOString();
    const { error } = await supabaseAdmin.from("orders").update(patch).eq("id", data.orderId);
    if (error) throw new Error(error.message);
    return { ok: true as const };
  });

export const adminGetPricing = createServerFn({ method: "GET" }).handler(async () => {
  await gate();
  const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
  const { data } = await supabaseAdmin.from("pricing_settings").select("*").eq("id", 1).single();
  return data;
});

const PricingInput = z.object({
  usd_per_credit: z.coerce.number().positive(),
  iqd_per_usd: z.coerce.number().positive(),
  tier_pdf_iqd: z.coerce.number().int().nonnegative(),
  tier_printed_iqd: z.coerce.number().int().nonnegative(),
  tier_video_iqd: z.coerce.number().int().nonnegative(),
  print_cost_iqd: z.coerce.number().int().nonnegative(),
  shipping_cost_iqd: z.coerce.number().int().nonnegative(),
});

export const adminUpdatePricing = createServerFn({ method: "POST" })
  .inputValidator((d: unknown) => PricingInput.parse(d))
  .handler(async ({ data }) => {
    await gate();
    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
    const { error } = await supabaseAdmin.from("pricing_settings").update(data).eq("id", 1);
    if (error) throw new Error(error.message);
    return { ok: true as const };
  });

export const adminAnalytics = createServerFn({ method: "GET" }).handler(async () => {
  await gate();
  const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
  const { data: costs } = await supabaseAdmin
    .from("order_costs_v")
    .select("revenue_iqd, cost_iqd, gross_profit_iqd, status, tier");
  const rows = costs ?? [];
  let revenue = 0, cost = 0, profit = 0;
  for (const r of rows) {
    if (r.status === "paid" || r.status === "delivered") {
      revenue += Number(r.revenue_iqd) || 0;
      profit += Number(r.gross_profit_iqd) || 0;
    }
    cost += Number(r.cost_iqd) || 0;
  }
  return {
    total_revenue_iqd: revenue,
    total_cost_iqd: cost,
    total_profit_iqd: profit,
    total_orders: rows.length,
    by_tier: {
      pdf: rows.filter((r) => r.tier === "pdf").length,
      printed: rows.filter((r) => r.tier === "printed").length,
      video: rows.filter((r) => r.tier === "video").length,
    },
  };
});
