/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MyOrdersRouteImport } from './routes/my-orders'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as CreateRouteImport } from './routes/create'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PreviewOrderIdRouteImport } from './routes/preview.$orderId'
import { Route as AdminVideosRouteImport } from './routes/admin.videos'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminThemesRouteImport } from './routes/admin.themes'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AdminOrdersIdRouteImport } from './routes/admin.orders.$id'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const MyOrdersRoute = MyOrdersRouteImport.update({
  id: '/my-orders',
  path: '/my-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PreviewOrderIdRoute = PreviewOrderIdRouteImport.update({
  id: '/preview/$orderId',
  path: '/preview/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVideosRoute = AdminVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminThemesRoute = AdminThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AdminRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/mcp': typeof McpRoute
  '/my-orders': typeof MyOrdersRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/themes': typeof AdminThemesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/preview/$orderId': typeof PreviewOrderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/mcp': typeof McpRoute
  '/my-orders': typeof MyOrdersRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/themes': typeof AdminThemesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/preview/$orderId': typeof PreviewOrderIdRoute
  '/admin': typeof AdminIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/mcp': typeof McpRoute
  '/my-orders': typeof MyOrdersRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/themes': typeof AdminThemesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/preview/$orderId': typeof PreviewOrderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/create'
    | '/mcp'
    | '/my-orders'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/analytics'
    | '/admin/content'
    | '/admin/coupons'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/themes'
    | '/admin/users'
    | '/admin/videos'
    | '/preview/$orderId'
    | '/admin/'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/orders/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/create'
    | '/mcp'
    | '/my-orders'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/analytics'
    | '/admin/content'
    | '/admin/coupons'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/themes'
    | '/admin/users'
    | '/admin/videos'
    | '/preview/$orderId'
    | '/admin'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/orders/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/create'
    | '/mcp'
    | '/my-orders'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/analytics'
    | '/admin/content'
    | '/admin/coupons'
    | '/admin/login'
    | '/admin/settings'
    | '/admin/themes'
    | '/admin/users'
    | '/admin/videos'
    | '/preview/$orderId'
    | '/admin/'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/orders/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CreateRoute: typeof CreateRoute
  McpRoute: typeof McpRoute
  MyOrdersRoute: typeof MyOrdersRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  PreviewOrderIdRoute: typeof PreviewOrderIdRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/my-orders': {
      id: '/my-orders'
      path: '/my-orders'
      fullPath: '/my-orders'
      preLoaderRoute: typeof MyOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/preview/$orderId': {
      id: '/preview/$orderId'
      path: '/preview/$orderId'
      fullPath: '/preview/$orderId'
      preLoaderRoute: typeof PreviewOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/videos': {
      id: '/admin/videos'
      path: '/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AdminVideosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/themes': {
      id: '/admin/themes'
      path: '/themes'
      fullPath: '/admin/themes'
      preLoaderRoute: typeof AdminThemesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/orders/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminThemesRoute: typeof AdminThemesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVideosRoute: typeof AdminVideosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminThemesRoute: AdminThemesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVideosRoute: AdminVideosRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminOrdersIdRoute: AdminOrdersIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CreateRoute: CreateRoute,
  McpRoute: McpRoute,
  MyOrdersRoute: MyOrdersRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  PreviewOrderIdRoute: PreviewOrderIdRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
