/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MyOrdersRouteImport } from './routes/my-orders'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as CreateRouteImport } from './routes/create'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as STokenRouteImport } from './routes/s.$token'
import { Route as PreviewOrderIdRouteImport } from './routes/preview.$orderId'
import { Route as AdminVideosRouteImport } from './routes/admin.videos'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminThemesRouteImport } from './routes/admin.themes'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminTemplatesRouteImport } from './routes/admin.templates'
import { Route as AdminShareEventsRouteImport } from './routes/admin.share-events'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReferralsRouteImport } from './routes/admin.referrals'
import { Route as AdminRedownloadsRouteImport } from './routes/admin.redownloads'
import { Route as AdminPhoneBansRouteImport } from './routes/admin.phone-bans'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminJobsRouteImport } from './routes/admin.jobs'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminFlagsRouteImport } from './routes/admin.flags'
import { Route as AdminEmergencyRouteImport } from './routes/admin.emergency'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminCachesRouteImport } from './routes/admin.caches'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAudioRouteImport } from './routes/admin.audio'
import { Route as AdminArtStylesRouteImport } from './routes/admin.art-styles'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAiModelsRouteImport } from './routes/admin.ai-models'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AdminOrdersIdRouteImport } from './routes/admin.orders.$id'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicShareCardsTokenRouteImport } from './routes/api/public/share-cards/$token'
import { Route as ApiPublicHooksJobsTickRouteImport } from './routes/api/public/hooks/jobs-tick'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MyOrdersRoute = MyOrdersRouteImport.update({
  id: '/my-orders',
  path: '/my-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewOrderIdRoute = PreviewOrderIdRouteImport.update({
  id: '/preview/$orderId',
  path: '/preview/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVideosRoute = AdminVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminThemesRoute = AdminThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShareEventsRoute = AdminShareEventsRouteImport.update({
  id: '/share-events',
  path: '/share-events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReferralsRoute = AdminReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRedownloadsRoute = AdminRedownloadsRouteImport.update({
  id: '/redownloads',
  path: '/redownloads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPhoneBansRoute = AdminPhoneBansRouteImport.update({
  id: '/phone-bans',
  path: '/phone-bans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFlagsRoute = AdminFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmergencyRoute = AdminEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCachesRoute = AdminCachesRouteImport.update({
  id: '/caches',
  path: '/caches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAudioRoute = AdminAudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArtStylesRoute = AdminArtStylesRouteImport.update({
  id: '/art-styles',
  path: '/art-styles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiModelsRoute = AdminAiModelsRouteImport.update({
  id: '/ai-models',
  path: '/ai-models',
  getParentRoute: () => AdminRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AdminRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicShareCardsTokenRoute =
  ApiPublicShareCardsTokenRouteImport.update({
    id: '/api/public/share-cards/$token',
    path: '/api/public/share-cards/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksJobsTickRoute = ApiPublicHooksJobsTickRouteImport.update({
  id: '/api/public/hooks/jobs-tick',
  path: '/api/public/hooks/jobs-tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/family': typeof FamilyRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/how-it-works': typeof HowItWorksRoute
  '/mcp': typeof McpRoute
  '/my-orders': typeof MyOrdersRoute
  '/pricing': typeof PricingRoute
  '/referrals': typeof ReferralsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/videos': typeof VideosRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/ai-models': typeof AdminAiModelsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/art-styles': typeof AdminArtStylesRoute
  '/admin/audio': typeof AdminAudioRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/caches': typeof AdminCachesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/emergency': typeof AdminEmergencyRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/phone-bans': typeof AdminPhoneBansRoute
  '/admin/redownloads': typeof AdminRedownloadsRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/share-events': typeof AdminShareEventsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/themes': typeof AdminThemesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/preview/$orderId': typeof PreviewOrderIdRoute
  '/s/$token': typeof STokenRoute
  '/admin/': typeof AdminIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/api/public/hooks/jobs-tick': typeof ApiPublicHooksJobsTickRoute
  '/api/public/share-cards/$token': typeof ApiPublicShareCardsTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/family': typeof FamilyRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/how-it-works': typeof HowItWorksRoute
  '/mcp': typeof McpRoute
  '/my-orders': typeof MyOrdersRoute
  '/pricing': typeof PricingRoute
  '/referrals': typeof ReferralsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/videos': typeof VideosRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/ai-models': typeof AdminAiModelsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/art-styles': typeof AdminArtStylesRoute
  '/admin/audio': typeof AdminAudioRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/caches': typeof AdminCachesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/emergency': typeof AdminEmergencyRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/phone-bans': typeof AdminPhoneBansRoute
  '/admin/redownloads': typeof AdminRedownloadsRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/share-events': typeof AdminShareEventsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/themes': typeof AdminThemesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/preview/$orderId': typeof PreviewOrderIdRoute
  '/s/$token': typeof STokenRoute
  '/admin': typeof AdminIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/api/public/hooks/jobs-tick': typeof ApiPublicHooksJobsTickRoute
  '/api/public/share-cards/$token': typeof ApiPublicShareCardsTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/family': typeof FamilyRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/how-it-works': typeof HowItWorksRoute
  '/mcp': typeof McpRoute
  '/my-orders': typeof MyOrdersRoute
  '/pricing': typeof PricingRoute
  '/referrals': typeof ReferralsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/videos': typeof VideosRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/ai-models': typeof AdminAiModelsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/art-styles': typeof AdminArtStylesRoute
  '/admin/audio': typeof AdminAudioRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/caches': typeof AdminCachesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/emergency': typeof AdminEmergencyRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/phone-bans': typeof AdminPhoneBansRoute
  '/admin/redownloads': typeof AdminRedownloadsRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/share-events': typeof AdminShareEventsRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/themes': typeof AdminThemesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/preview/$orderId': typeof PreviewOrderIdRoute
  '/s/$token': typeof STokenRoute
  '/admin/': typeof AdminIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/api/public/hooks/jobs-tick': typeof ApiPublicHooksJobsTickRoute
  '/api/public/share-cards/$token': typeof ApiPublicShareCardsTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/create'
    | '/family'
    | '/faq'
    | '/gallery'
    | '/how-it-works'
    | '/mcp'
    | '/my-orders'
    | '/pricing'
    | '/referrals'
    | '/sitemap.xml'
    | '/testimonials'
    | '/videos'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/ai-models'
    | '/admin/analytics'
    | '/admin/art-styles'
    | '/admin/audio'
    | '/admin/audit'
    | '/admin/caches'
    | '/admin/content'
    | '/admin/coupons'
    | '/admin/emergency'
    | '/admin/flags'
    | '/admin/gallery'
    | '/admin/jobs'
    | '/admin/login'
    | '/admin/phone-bans'
    | '/admin/redownloads'
    | '/admin/referrals'
    | '/admin/settings'
    | '/admin/share-events'
    | '/admin/templates'
    | '/admin/testimonials'
    | '/admin/themes'
    | '/admin/users'
    | '/admin/videos'
    | '/preview/$orderId'
    | '/s/$token'
    | '/admin/'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/orders/$id'
    | '/api/public/hooks/jobs-tick'
    | '/api/public/share-cards/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/create'
    | '/family'
    | '/faq'
    | '/gallery'
    | '/how-it-works'
    | '/mcp'
    | '/my-orders'
    | '/pricing'
    | '/referrals'
    | '/sitemap.xml'
    | '/testimonials'
    | '/videos'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/ai-models'
    | '/admin/analytics'
    | '/admin/art-styles'
    | '/admin/audio'
    | '/admin/audit'
    | '/admin/caches'
    | '/admin/content'
    | '/admin/coupons'
    | '/admin/emergency'
    | '/admin/flags'
    | '/admin/gallery'
    | '/admin/jobs'
    | '/admin/login'
    | '/admin/phone-bans'
    | '/admin/redownloads'
    | '/admin/referrals'
    | '/admin/settings'
    | '/admin/share-events'
    | '/admin/templates'
    | '/admin/testimonials'
    | '/admin/themes'
    | '/admin/users'
    | '/admin/videos'
    | '/preview/$orderId'
    | '/s/$token'
    | '/admin'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/orders/$id'
    | '/api/public/hooks/jobs-tick'
    | '/api/public/share-cards/$token'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/create'
    | '/family'
    | '/faq'
    | '/gallery'
    | '/how-it-works'
    | '/mcp'
    | '/my-orders'
    | '/pricing'
    | '/referrals'
    | '/sitemap.xml'
    | '/testimonials'
    | '/videos'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/ai-models'
    | '/admin/analytics'
    | '/admin/art-styles'
    | '/admin/audio'
    | '/admin/audit'
    | '/admin/caches'
    | '/admin/content'
    | '/admin/coupons'
    | '/admin/emergency'
    | '/admin/flags'
    | '/admin/gallery'
    | '/admin/jobs'
    | '/admin/login'
    | '/admin/phone-bans'
    | '/admin/redownloads'
    | '/admin/referrals'
    | '/admin/settings'
    | '/admin/share-events'
    | '/admin/templates'
    | '/admin/testimonials'
    | '/admin/themes'
    | '/admin/users'
    | '/admin/videos'
    | '/preview/$orderId'
    | '/s/$token'
    | '/admin/'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/orders/$id'
    | '/api/public/hooks/jobs-tick'
    | '/api/public/share-cards/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CreateRoute: typeof CreateRoute
  FamilyRoute: typeof FamilyRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  HowItWorksRoute: typeof HowItWorksRoute
  McpRoute: typeof McpRoute
  MyOrdersRoute: typeof MyOrdersRoute
  PricingRoute: typeof PricingRoute
  ReferralsRoute: typeof ReferralsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TestimonialsRoute: typeof TestimonialsRoute
  VideosRoute: typeof VideosRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  PreviewOrderIdRoute: typeof PreviewOrderIdRoute
  STokenRoute: typeof STokenRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicHooksJobsTickRoute: typeof ApiPublicHooksJobsTickRoute
  ApiPublicShareCardsTokenRoute: typeof ApiPublicShareCardsTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-orders': {
      id: '/my-orders'
      path: '/my-orders'
      fullPath: '/my-orders'
      preLoaderRoute: typeof MyOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$orderId': {
      id: '/preview/$orderId'
      path: '/preview/$orderId'
      fullPath: '/preview/$orderId'
      preLoaderRoute: typeof PreviewOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/videos': {
      id: '/admin/videos'
      path: '/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AdminVideosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/themes': {
      id: '/admin/themes'
      path: '/themes'
      fullPath: '/admin/themes'
      preLoaderRoute: typeof AdminThemesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/share-events': {
      id: '/admin/share-events'
      path: '/share-events'
      fullPath: '/admin/share-events'
      preLoaderRoute: typeof AdminShareEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/referrals': {
      id: '/admin/referrals'
      path: '/referrals'
      fullPath: '/admin/referrals'
      preLoaderRoute: typeof AdminReferralsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/redownloads': {
      id: '/admin/redownloads'
      path: '/redownloads'
      fullPath: '/admin/redownloads'
      preLoaderRoute: typeof AdminRedownloadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/phone-bans': {
      id: '/admin/phone-bans'
      path: '/phone-bans'
      fullPath: '/admin/phone-bans'
      preLoaderRoute: typeof AdminPhoneBansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/flags': {
      id: '/admin/flags'
      path: '/flags'
      fullPath: '/admin/flags'
      preLoaderRoute: typeof AdminFlagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/emergency': {
      id: '/admin/emergency'
      path: '/emergency'
      fullPath: '/admin/emergency'
      preLoaderRoute: typeof AdminEmergencyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/caches': {
      id: '/admin/caches'
      path: '/caches'
      fullPath: '/admin/caches'
      preLoaderRoute: typeof AdminCachesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audio': {
      id: '/admin/audio'
      path: '/audio'
      fullPath: '/admin/audio'
      preLoaderRoute: typeof AdminAudioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/art-styles': {
      id: '/admin/art-styles'
      path: '/art-styles'
      fullPath: '/admin/art-styles'
      preLoaderRoute: typeof AdminArtStylesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-models': {
      id: '/admin/ai-models'
      path: '/ai-models'
      fullPath: '/admin/ai-models'
      preLoaderRoute: typeof AdminAiModelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/orders/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/share-cards/$token': {
      id: '/api/public/share-cards/$token'
      path: '/api/public/share-cards/$token'
      fullPath: '/api/public/share-cards/$token'
      preLoaderRoute: typeof ApiPublicShareCardsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/jobs-tick': {
      id: '/api/public/hooks/jobs-tick'
      path: '/api/public/hooks/jobs-tick'
      fullPath: '/api/public/hooks/jobs-tick'
      preLoaderRoute: typeof ApiPublicHooksJobsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAiModelsRoute: typeof AdminAiModelsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminArtStylesRoute: typeof AdminArtStylesRoute
  AdminAudioRoute: typeof AdminAudioRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCachesRoute: typeof AdminCachesRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminEmergencyRoute: typeof AdminEmergencyRoute
  AdminFlagsRoute: typeof AdminFlagsRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPhoneBansRoute: typeof AdminPhoneBansRoute
  AdminRedownloadsRoute: typeof AdminRedownloadsRoute
  AdminReferralsRoute: typeof AdminReferralsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminShareEventsRoute: typeof AdminShareEventsRoute
  AdminTemplatesRoute: typeof AdminTemplatesRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminThemesRoute: typeof AdminThemesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVideosRoute: typeof AdminVideosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiModelsRoute: AdminAiModelsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminArtStylesRoute: AdminArtStylesRoute,
  AdminAudioRoute: AdminAudioRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCachesRoute: AdminCachesRoute,
  AdminContentRoute: AdminContentRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminEmergencyRoute: AdminEmergencyRoute,
  AdminFlagsRoute: AdminFlagsRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPhoneBansRoute: AdminPhoneBansRoute,
  AdminRedownloadsRoute: AdminRedownloadsRoute,
  AdminReferralsRoute: AdminReferralsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminShareEventsRoute: AdminShareEventsRoute,
  AdminTemplatesRoute: AdminTemplatesRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminThemesRoute: AdminThemesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVideosRoute: AdminVideosRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminOrdersIdRoute: AdminOrdersIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CreateRoute: CreateRoute,
  FamilyRoute: FamilyRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  HowItWorksRoute: HowItWorksRoute,
  McpRoute: McpRoute,
  MyOrdersRoute: MyOrdersRoute,
  PricingRoute: PricingRoute,
  ReferralsRoute: ReferralsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TestimonialsRoute: TestimonialsRoute,
  VideosRoute: VideosRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  PreviewOrderIdRoute: PreviewOrderIdRoute,
  STokenRoute: STokenRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicHooksJobsTickRoute: ApiPublicHooksJobsTickRoute,
  ApiPublicShareCardsTokenRoute: ApiPublicShareCardsTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
